use actix_web::{web, App, HttpServer, Responder, Result, Error, HttpResponse};
use actix_web::dev::{ServiceRequest, ServiceResponse, Service, Transform};
use actix_cors::Cors;
use sqlx::{PgPool, Row};
use std::future::{ready, Ready};
use futures_util::future::LocalBoxFuture;

async fn index() -> impl Responder {
    "Hello from Actix Web!"
}

async fn health() -> impl Responder {
    "OK"
}

async fn name(path: web::Path<String>) -> impl Responder {
    format!("Hello, {}!", path.into_inner())
}

async fn db_check(pool: web::Data<PgPool>) -> Result<impl Responder> {
    let result = sqlx::query("SELECT NOW() as current_time, version() as pg_version")
        .fetch_one(pool.get_ref())
        .await;

    match result {
        Ok(row) => {
            let current_time: chrono::DateTime<chrono::Utc> = row.get("current_time");
            let pg_version: String = row.get("pg_version");
            Ok(format!(
                "Database connected!\nPostgreSQL version: {}\nCurrent time: {}",
                pg_version, current_time
            ))
        }
        Err(e) => Ok(format!("Database error: {}", e)),
    }
}

// Authorization Middleware
pub struct AuthMiddleware {
    expected_api_key: String,
}

impl AuthMiddleware {
    pub fn new(expected_api_key: String) -> Self {
        AuthMiddleware { expected_api_key }
    }
}

impl<S, B> Transform<S, ServiceRequest> for AuthMiddleware
where
    S: Service<ServiceRequest, Response = ServiceResponse<B>, Error = Error>,
    S::Future: 'static,
    B: 'static,
{
    type Response = ServiceResponse<B>;
    type Error = Error;
    type InitError = ();
    type Transform = AuthMiddlewareService<S>;
    type Future = Ready<Result<Self::Transform, Self::InitError>>;

    fn new_transform(&self, service: S) -> Self::Future {
        ready(Ok(AuthMiddlewareService {
            service,
            expected_api_key: self.expected_api_key.clone(),
        }))
    }
}

pub struct AuthMiddlewareService<S> {
    service: S,
    expected_api_key: String,
}

impl<S, B> Service<ServiceRequest> for AuthMiddlewareService<S>
where
    S: Service<ServiceRequest, Response = ServiceResponse<B>, Error = Error>,
    S::Future: 'static,
    B: 'static,
{
    type Response = ServiceResponse<B>;
    type Error = Error;
    type Future = LocalBoxFuture<'static, Result<Self::Response, Self::Error>>;

    actix_web::dev::forward_ready!(service);

    fn call(&self, req: ServiceRequest) -> Self::Future {
        let expected_key = self.expected_api_key.clone();
        
        // Check for x-api-key header
        let auth_header = req.headers().get("x-api-key");
        
        match auth_header {
            Some(header_value) if header_value.to_str().unwrap_or("") == expected_key => {
                // Valid API key, proceed
                let fut = self.service.call(req);
                Box::pin(async move {
                    let res = fut.await?;
                    Ok(res)
                })
            }
            _ => {
                // Invalid or missing API key
                Box::pin(async move {
                    Err(actix_web::error::ErrorUnauthorized("Invalid or missing x-api-key header"))
                })
            }
        }
    }
}

// Generated by setup-db.sh - DO NOT EDIT MANUALLY
// Table: statustracker_table

#[derive(Debug, serde::Serialize, serde::Deserialize, sqlx::FromRow)]
pub struct StatustrackerRecord {
    pub id: i32,
    pub created_on: chrono::DateTime<chrono::Utc>,
    pub changed_on: chrono::DateTime<chrono::Utc>,
    pub name: String,
    pub status: String,
}

#[derive(serde::Deserialize)]
pub struct CreateStatustrackerRecordRequest {
    pub name: String,
    pub status: String,
}

// Scoreboard structs
#[derive(Debug, serde::Serialize, serde::Deserialize, sqlx::FromRow)]
pub struct ScoreboardEntry {
    pub id: i32,
    pub name: String,
    pub score: i32,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub is_top_10: bool,
}

#[derive(Debug, serde::Serialize, sqlx::FromRow)]
pub struct TopScoreEntry {
    pub rank: i64,
    pub id: i32,
    pub name: String,
    pub score: i32,
    pub created_at: chrono::DateTime<chrono::Utc>,
}

#[derive(serde::Deserialize)]
pub struct EnterScoreRequest {
    pub name: String,
    pub score: i32,
}

#[derive(serde::Serialize)]
pub struct EmptyScoreboardResponse {
    pub message: String,
    pub deleted_count: i32,
}

// CRUD operations
async fn create_statustracker(
    pool: web::Data<PgPool>,
    record: web::Json<CreateStatustrackerRecordRequest>,
) -> Result<impl Responder> {
    let fields: Vec<&str> = vec![
        "name",
        "status",
    ];
    let fields_str = fields.join(", ");
    let placeholders: Vec<String> = (1..=fields.len()).map(|i| format!("${}", i)).collect();
    let values_str = placeholders.join(", ");
    let query = format!("INSERT INTO statustracker_table ({}) VALUES ({}) RETURNING *", fields_str, values_str);

    let result = sqlx::query_as::<_, StatustrackerRecord>(&query)
        .bind(&record.name)
        .bind(&record.status)
        .fetch_one(pool.get_ref())
        .await;

    match result {
        Ok(record) => Ok(web::Json(record)),
        Err(e) => {
            eprintln!("Database error: {}", e);
            Err(actix_web::error::ErrorInternalServerError("Failed to create record"))
        }
    }
}

async fn get_statustracker(
    pool: web::Data<PgPool>,
    id: web::Path<i32>,
) -> Result<impl Responder> {
    let result = sqlx::query_as::<_, StatustrackerRecord>(
        "SELECT * FROM statustracker_table WHERE id = $1"
    )
    .bind(id.into_inner())
    .fetch_optional(pool.get_ref())
    .await;

    match result {
        Ok(Some(record)) => Ok(web::Json(record)),
        Ok(None) => Err(actix_web::error::ErrorNotFound("Record not found")),
        Err(e) => {
            eprintln!("Database error: {}", e);
            Err(actix_web::error::ErrorInternalServerError("Failed to get record"))
        }
    }
}

async fn list_statustracker(
    pool: web::Data<PgPool>,
) -> Result<impl Responder> {
    let result = sqlx::query_as::<_, StatustrackerRecord>(
        "SELECT * FROM statustracker_table ORDER BY id"
    )
    .fetch_all(pool.get_ref())
    .await;

    match result {
        Ok(records) => Ok(web::Json(records)),
        Err(e) => {
            eprintln!("Database error: {}", e);
            Err(actix_web::error::ErrorInternalServerError("Failed to list records"))
        }
    }
}

async fn update_statustracker(
    pool: web::Data<PgPool>,
    id: web::Path<i32>,
    record: web::Json<CreateStatustrackerRecordRequest>,
) -> Result<impl Responder> {
    let field_names: Vec<&str> = vec![
        "name",
        "status",
    ];
    let set_clauses: Vec<String> = field_names.iter().enumerate().map(|(i, name)| format!("{} = ${}", name, i + 2)).collect();
    let set_clause = set_clauses.join(", ");
    let query = format!("UPDATE statustracker_table SET {} WHERE id = $1 RETURNING *", set_clause);

    let result = sqlx::query_as::<_, StatustrackerRecord>(&query)
        .bind(id.into_inner())
        .bind(&record.name)
        .bind(&record.status)
        .fetch_optional(pool.get_ref())
        .await;

    match result {
        Ok(Some(record)) => Ok(web::Json(record)),
        Ok(None) => Err(actix_web::error::ErrorNotFound("Record not found")),
        Err(e) => {
            eprintln!("Database error: {}", e);
            Err(actix_web::error::ErrorInternalServerError("Failed to update record"))
        }
    }
}

async fn delete_statustracker(
    pool: web::Data<PgPool>,
    id: web::Path<i32>,
) -> Result<impl Responder> {
    let result = sqlx::query("DELETE FROM statustracker_table WHERE id = $1")
        .bind(id.into_inner())
        .execute(pool.get_ref())
        .await;

    match result {
        Ok(rows) => {
            if rows.rows_affected() > 0 {
                Ok(web::Json(serde_json::json!({"message": "Record deleted"})))
            } else {
                Err(actix_web::error::ErrorNotFound("Record not found"))
            }
        }
        Err(e) => {
            eprintln!("Database error: {}", e);
            Err(actix_web::error::ErrorInternalServerError("Failed to delete record"))
        }
    }
}

// Scoreboard API endpoints

async fn enter_score(
    pool: web::Data<PgPool>,
    request: web::Json<EnterScoreRequest>,
) -> Result<impl Responder> {
    let result = sqlx::query_as::<_, ScoreboardEntry>(
        "SELECT * FROM insert_scoreboard_entry($1, $2)"
    )
    .bind(&request.name)
    .bind(request.score)
    .fetch_one(pool.get_ref())
    .await;

    match result {
        Ok(entry) => {
            println!("New score entered: {} scored {} (Top 10: {})", entry.name, entry.score, entry.is_top_10);
            Ok(web::Json(entry))
        }
        Err(e) => {
            eprintln!("Database error: {}", e);
            Err(actix_web::error::ErrorInternalServerError("Failed to enter score"))
        }
    }
}

async fn show_scores(
    pool: web::Data<PgPool>,
) -> Result<impl Responder> {
    let result = sqlx::query_as::<_, TopScoreEntry>(
        "SELECT * FROM get_top_10_scores()"
    )
    .fetch_all(pool.get_ref())
    .await;

    match result {
        Ok(scores) => Ok(web::Json(scores)),
        Err(e) => {
            eprintln!("Database error: {}", e);
            Err(actix_web::error::ErrorInternalServerError("Failed to retrieve scores"))
        }
    }
}

async fn empty_scoreboard(
    pool: web::Data<PgPool>,
) -> Result<impl Responder> {
    let result = sqlx::query_scalar::<_, i32>(
        "SELECT empty_scoreboard()"
    )
    .fetch_one(pool.get_ref())
    .await;

    match result {
        Ok(deleted_count) => {
            println!("Scoreboard emptied: {} entries deleted", deleted_count);
            Ok(web::Json(EmptyScoreboardResponse {
                message: format!("Scoreboard cleared successfully"),
                deleted_count,
            }))
        }
        Err(e) => {
            eprintln!("Database error: {}", e);
            Err(actix_web::error::ErrorInternalServerError("Failed to empty scoreboard"))
        }
    }
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    // Database connection string
    // From within Docker network, use service name: statustracker-postgres
    // From host machine, use: localhost:5433
    let database_url = std::env::var("DATABASE_URL")
        .unwrap_or_else(|_| "postgresql://statustracker_user:qwertz@statustracker-postgres:5432/statustracker_db".to_string());

    // Create database connection pool
    let pool = PgPool::connect(&database_url)
        .await
        .expect("Failed to connect to database");

    // Test the connection
    sqlx::query("SELECT 1")
        .execute(&pool)
        .await
        .expect("Failed to execute test query");

    println!("✓ Database connection established");

    // API key for authorization
    let api_key = "statustracker-apisecret".to_string();
    println!("===========================================");
    println!("✓ x-api-key: {}", api_key);
    println!("===========================================");

    HttpServer::new(move || {
        // Configure CORS - Allow all origins with credentials
        let cors = Cors::default()
            .allow_any_origin()
            .allowed_methods(vec!["GET", "POST", "PUT", "DELETE", "OPTIONS"])
            .allowed_headers(vec![
                actix_web::http::header::CONTENT_TYPE,
                actix_web::http::header::HeaderName::from_static("x-api-key"),
            ])
            .supports_credentials()
            .max_age(3600);

        App::new()
            .wrap(cors)  // CORS middleware (applied first, outermost)
            .app_data(web::Data::new(pool.clone()))
            .service(
                web::scope("/api")
                    .wrap(AuthMiddleware::new(api_key.clone()))  // Auth middleware (applied after CORS)
                    .route("/name/{name}", web::get().to(name))
                    .route("/db", web::get().to(db_check))
                .route("/statustracker", web::post().to(create_statustracker))
                .route("/statustracker", web::get().to(list_statustracker))
                .route("/statustracker/{id}", web::get().to(get_statustracker))
                .route("/statustracker/{id}", web::put().to(update_statustracker))
                .route("/statustracker/{id}", web::delete().to(delete_statustracker))
                // Scoreboard endpoints
                .route("/scoreboard/enter_score", web::post().to(enter_score))
                .route("/scoreboard/show_scores", web::get().to(show_scores))
                .route("/scoreboard/empty_scoreboard", web::delete().to(empty_scoreboard))
            )
            .route("/health", web::get().to(health))
            .route("/", web::get().to(index))
    })
    .bind("0.0.0.0:8080")?
    .run()
    .await
}
